/**:
  ros__parameters:
    pcap_dir_path: /home/ataparlar/data/task_spesific/hesai_parser/bomonti_1/pcaps/
    pose_txt_path: /home/ataparlar/data/task_spesific/hesai_parser/bomonti_1/bomonti1.txt
    pcd_export_directory: /home/ataparlar/data/task_spesific/hesai_parser/bomonti_1/output/

    project_namespace: bomonti

    map_origin_x: 665923.553
    map_origin_y: 4547027.817
    map_origin_z: 82.26980721453911

    imu2lidar_roll: -179.582
    imu2lidar_pitch: 0.411
    imu2lidar_yaw: 179.533

    enable_ned2enu: true
    voxel_resolution: 0.2
    save_pcd: false